string path             # get prims at path
---
string[] paths          # list of prim paths
string[] types          # prim type names
bool success            # indicate a successful execution of the service
string message          # informational, e.g. for error messages