/**:
  ros__parameters:
    planning_plugin: ompl_interface/OMPLPlanner
    request_adapters: >-
      default_planner_request_adapters/AddTimeOptimalParameterization
      default_planner_request_adapters/ResolveConstraintFrames
      default_planner_request_adapters/FixWorkspaceBounds
      default_planner_request_adapters/FixStartStateBounds
      default_planner_request_adapters/FixStartStateCollision
      default_planner_request_adapters/FixStartStatePathConstraints
    start_state_max_bounds_error: 0.1
    planner_configs:
      RRTConnectkConfigDefault:
        type: geometric::RRTConnect
        range: 0.0
    ur_manipulator:
      planner_configs:
        - RRTConnectkConfigDefault
      default_planner_config: RRTConnectkConfigDefault
